[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clickcrate_test = "9A14uKSX7DgPPH6Z8GumDewQ97Jn6riBxSKvnrJsM9vA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ap/solana-wallets/clickcrate-wallet.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
